import turtle
mypen=turtle.Turtle()
mypen.shape("turtle")
mypen.speed(2)
turtle.bgcolor("black")
mypen.color('#C0C0C0')
mypen.pensize(7)
def logo():
    mypen.circle(154)
    mypen.left(90)
    mypen.penup()
    mypen.pensize(15)
    mypen.forward(150)
    mypen.pendown()
    mypen.forward(150)
    mypen.penup()
    mypen.forward(-150)
    mypen.left(120)
    mypen.pendown()
    mypen.forward(150)
    mypen.penup()
    mypen.forward(-150)
    mypen.left(120)
    mypen.pendown()
    mypen.forward(150)
    mypen.penup()
    mypen.forward(-150)
    mypen.left(120)
    mypen.hideturtle()
    mypen.pendown()
    mypen.write("Mercedes Logo",font=('italic',50,"bold"))
logo()
turtle.done()
    
    
    
